### ISSUE TITLE
Logger info error

### ISSUE THREAD

**Issue by pcuellar** [brandur/mastodon-cross-post#2]
Thanks for putting this together, looking forward to using it. 
Let me preface by saying I am not familiar with Go. I tried to running the tool but kept getting an error that seems connected to how the logging is done:

```
# command-line-arguments
./main.go:88:15: undefined: LeveledLogger
./main.go:88:36: undefined: LevelInfo
```

Maybe the level logging package is deprecated? I found this update on the package which seems to suggests so https://pkg.go.dev/github.com/go-kit/kit/log/level 

I tried to re-implement the logging that way but wasn't able to get it running. 

I am on MacOs Ventura 13.1. Go version go1.19.4

**Comment by brandur** [comment]
> Thanks for putting this together, looking forward to using it.

Thanks @pcuellar!

I think the problem is that you're trying to run it with `go run main.go` which will only use `main.go` as an input file. `LeveledLogger` is defined in `logger.go` which is in the same package, but in a different file. This will work:

``` sh
$ go build .
$ ./mastodon-cross-post
```

Just FYI — this project is kind of "me-ware" in that it's pretty customized to my particular uses. You could probably get it up and running, but I kinda suspect you're eventually going to find that it's got missing features that you want for your specific needs.

**Comment by pcuellar** [comment]
Aha! I knew there was something I was doing wrong. I can build it now. Thanks for the _"me-aware"_ disclosure. The options I found online had more than I was looking for so maybe this minimal take is what I am looking for :)
